version: "3"

services:
  web: 
    container_name: tiendaapp
    restart: always
    build: .
    ports: 
      - "4000:3000"
    links: 
      - mongo
  mongo:
    container_name: mongodatabase
    image: mongo
    ports:
      - "27018:27017"